### ISSUE TITLE
Refresh web page endlessly. [vue-component] [METEOR@1.8]

### ISSUE THREAD

**Issue by mahadoang** [meteor-vue/vue-meteor#331] opened 2018-10-08 05:22 UTC
add akryum:vue-component to project

METEOR@1.8

How to fixed
Refresh web page endlessly.

**Comment by runarberg** [comment] 2018-10-08 11:30
Has been noted as comments in #326.

**Comment by Akryum** [comment] 2018-10-08 19:44
Duplicate of #326

**Closed by Akryum** 2018-10-08 19:44 UTC
