### ISSUE TITLE
.vue components in /imports get auto loaded even when they are not referenced

### ISSUE THREAD

**Issue by christophmayrhofer** [meteor-vue/vue-meteor#193] opened 2017-06-01 10:27 UTC
All my .vue components end up in the app bundle. Even when I place them in the imports folder and do not import them anywhere. Is this the expected behavior? I realized this when I tried to refactor for 1.5 dynamic imports

**Comment by Herteby** [comment] 2017-06-01 11:04
It's not intended behavior:
https://github.com/Akryum/vue-meteor/tree/master/packages/vue-component#automatic-components-registration

**Comment by christophmayrhofer** [comment] 2017-06-01 11:23
This only refers to the registration. I.e. the component tag (<todos></todos>) will be available without telling the parent component to use it:

import todos from './todos.vue'

export default {
components: { todos },
...
}

I meant  the file auto load in general (i.e. '/imports/todos.vue' gets parsed withour importing it)

**Comment by MKRazz** [comment] 2017-06-16 14:53
I noticed this too. It appears to be caused by `lazy: false` in the compiler plugin. I tested with `lazy: true` and it mostly seems to work but ran into some other issues that might be why it is false in the first place.

**Comment by Akryum** [comment] 2017-06-30 15:37
This should be fixed in `0.10.0`.

**Closed by Akryum** 2017-06-30 15:37 UTC
