### ISSUE TITLE
main.routes.js feature not working 

### ISSUE THREAD

**Issue by mikkelking** [meteor-vue/vue-meteor#401] opened 2020-05-10 04:04 UTC
Hi,

I created a file for the routes: `client/main.routes.js` using the syntax as suggested in the README. Here are the contents:

```
export default [
  {
    component: '/imports/pages/home.vue',
    path: "/home",
    name: "home",
  },
  {
    component: '/imports/pages/here.vue',
    path: "/here",
    name: "here",
  },
];
```

I get this error message:

```
main.routes.js:1 Uncaught TypeError: module.watch is not a function
    at module (main.routes.js:1)
    at fileEvaluate (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:346)
    at Module.require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:248)
    at require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:268)
    at app.js?hash=3a4b843d0c6a564a69f59f06a30a1bcf0b92558f:361
```

So it looks like the plugin is detecting the file, but the error stops it from working properly

Am I doing something wrong?

**Comment by chris-visser** [comment] 2020-06-07 21:40
I cannot reproduce this issue with the latest version of akryum:vue-router2. So I will close this for now since its been a while. Let me know if you still encounter the issue. Could you maybe add some more information?

**Closed by chris-visser** 2020-06-07 21:40 UTC
