### ISSUE TITLE
VS Code - page reloading after save, HRM fail

### ISSUE THREAD

**Issue by MartinBucko** [meteor-vue/vue-meteor#291] opened 2018-01-22 15:47 UTC
I'm facing weird problem with Visual Studio Code Editor. After save `.vue` file HRM don't update code, but instead app is rebuilded and page is reloaded. If i edit same file in sublime or by Chrome local file it works like i expected and code is update without page reload. I'm try also run vscode without extensions to check if some extensions don't save edited file twice with command 
`code --disable-extensions ./src/imports/ui/Home.vue`

Behavior was confirmed on actual `vue-meteor-demo` project.

`Linux Ubuntu 17.10 - VS Code v1.19.2`

**Comment by Akryum** [comment] 2018-12-09 12:40
I can't reproduce with my VS Code on elementary loki.

**Comment by mathieustan** [comment] 2019-04-01 08:50
It's an HRM issue from vue-component and more precisely from vue-component-dev-client. When you change anything from a vue component or any js files which are imported to a component, it'll rebuild/reload app. 

cf: https://github.com/meteor-vue/vue-meteor/issues/348

**Comment by Akryum** [comment] 2019-09-03 15:03
Should be fixed in latest release.

**Closed by Akryum** 2019-09-03 15:03 UTC
