### ISSUE TITLE
Uncaught Error: Cannot find module 'meteor-node-stubs/node_modules/http-browserify/lib/response'

### ISSUE THREAD

**Issue by xfkj** [meteor-vue/vue-meteor#315] opened 2018-04-26 01:26 UTC
the package meteor-stubs ^0.3.3 doesn't have such files indeed, I checked it.
 [in this line](https://github.com/meteor-vue/vue-meteor/blob/41228c434e96766f8ff2bc4b9e6b02a8546116a8/packages/vue-component-dev-client/client/dev-client.js#L9) you used it.

hope you can fix this, by the way, thanks for all you works in meteor and vue.

**Comment by mitar** [comment] 2018-05-03 22:19
See: https://github.com/meteor-vue/vue-meteor/pull/311

**Comment by mitar** [comment] 2018-05-03 22:20
Duplicate of #307.

**Closed by mitar** 2018-05-03 22:20 UTC
